apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-user
  name: backend-user
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
#    nodePort: 31002
#  type: NodePort
  selector:
    service: backend-user
