apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
#    nodePort: 31001
#  type: NodePort
  selector:
    service: backend-feed
