apiVersion: v1
kind: Service
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  ports:
  - name: "8100"
    port: 8100
    nodePort: 31000
    targetPort: 80
  type: NodePort
  selector:
    service: frontend
#  type: LoadBalancer    
